# Site settings
title: Space Apps NYC
email: organizers@spaceapps.nyc
description: The NYC chapter of NASA's International Space Apps Challenge
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://spaceapps.nyc" # the base hostname & protocol for your site

twitter_username: spaceappsnyc
github_username: spaceappsnyc
patreon_username: spaceappsnyc
meetup_username: Space-Apps-NYC

registrationIsOpen: true
registration_link: https://2019.spaceappschallenge.org/locations/new-york-city-ny/
livestreamIsOpen: false
livestream_link: "#livestream"
dates:
  - header: Begins
    timestamp: October_18_2019
  - header: Ends
    timestamp: October_20_2019
details:
  locations:
    - map: https://goo.gl/maps/s2ChbaFyHX4jcb3DA
      addressLine1: 46 E 70th St
      addressLine2: New York, NY 10021
      logo: images/explorers_club_logo.jpg
    - map: https://goo.gl/maps/aSRTvCAVD9tkSMfA7
      addressLine1: 215 Moore St
      addressLine2: Brooklyn, NY 11206
      logo: images/bushwick_generator_logo.jpg
year: 2019
member_count: 3000

# Build settings
markdown: kramdown
exclude:
  - vendor
  - archive
plugins:
  - github-pages

# Development
host: 0.0.0.0

# Event Schedule
# bootcamps:
  # - name: Space Apps Challenge Kickoff Cocktail Party
  #   image: /images/kickoff_cocktail_party.jpg
  #   location:
  #     name: The Mezzanine
  #     addressLine1: 55 Broadway
  #     addressLine2: New York, NY 10006
  #   date: October_06_2018
  #   info:
  #     - The Womensphere Global STEAMfest is a celebration of women harnessing the power of STEAM (science, technology, engineering, arts & design, mathematics) to create the future, and help achieve the Global Goals for Sustainable Development. Through the Womensphere Global STEAMfest, we are empowering women and girls all over the world through the Womensphere Global ARTfest, Womensphere Global CODEfest, and Womensphere Global VIDEOfest, kicking off this October 19-31.
  #     - Join us for a fun evening of cocktails, celebrating innovation, launching several exciting initiatives & connecting you with pioneering innovators in Silicon Alley!  
  #   schedule:
  #     - time: 4:00pm
  #       name: Check-in/registration & opening networking reception
  #     - time: 4:30pm
  #       name: Introductions & Opening networking reception & Open Bar
  #     - time: 4:45pm
  #       name: Welcome & Opening Remarks by Organizers - Analisa Leonor Balares (CEO, Womensphere) & Joseph Spens (Executive Director, Space Apps NYC)
  #     - time: 5:00pm
  #       name: Keynote — NASA, Vision for Innovation & Exploration, and The Most Vital Global Challenges of our Time – Dr. Gavin Schmidt, Director, NASA Goddard Institute
  #     - time: 5:15pm
  #       name: In Response to Global Challenges — Vision for Space Apps NYC & NASA Space Apps Challenges – Joseph Spens, Executive Director, Space Apps NYC
  #     - time: 5:25pm
  #       name: In Response to Global Challenges - Vision for the Womensphere Innovation Leadership Lab & Global STEAMfest- Analisa Balares, CEO & Chief Innovation Officer, Womensphere
  #     - time: 5:35pm
  #       name: In Response to Global Challenges - Emerging Markets Impact Investment & Inclusive Innovation – Maoi Arroyo, Serial Entrepreneur & General Partner, Ignite Impact Fund
  #     - time: 5:45pm
  #       name: Cocktail Invention & Mixology Lab - Interactive Workshop in Cocktail-Making – Hanne Madeleine Gates Paine, Cocktail Inventor & Program Director, Womensphere
  #     - time: 6:10pm
  #       name: Thousand Miles - A Global Journey in Music – Story & Music by Morley Shanti Kamen
  #     - time: 6:20pm
  #       name: Closing Remarks by Joseph Spens & Analisa Balares
  #     - time: 6:25pm
  #       name: Closing Networking Reception
  #   video: https://www.youtube.com/watch?v=urtWzphYr2w&t=4053s

judges:
  - name: Analisa Balares
    title: CEO & Chief Innovation Officer
    organization: Womensphere
    photo: Analisa Balares.jpeg
    bio:
      - Analisa Leonor Balares is Founder, CEO, and Chief Innovation Officer of Womensphere, a global platform for empowering women and girls to use STEAM, leadership, and innovation to create the future and help achieve the Global Goals for Sustainable Development. Analisa curates the Womensphere Summits &amp; Festivals, and leads building the Womensphere Innovation Leadership Lab, Womensphere Incubator Network, and Womensphere Foundation. Previously, Analisa worked in Wall Street for Goldman Sachs, Morgan Stanley, and Milestone Capital, and in technology and social media for Microsoft and 85 Broads (now Ellevate). She is an alumna of Harvard Business School, Mount Holyoke College, and Lester Pearson United World College,
      - Analisa is also a NASA Datanaut, and an organizer of the NASA Space Apps Global Challenge for NYC. She serves as a Commissioner of the Women’s Refugee Commission, Advisory Board Member of Music Beyond, Member of Women’s Forum of New York and International Women’s Forum, and Academy Member of the Global Teacher Prize. She also served as a Member of the Harvard Women’s Leadership Board, and L&#39;Oreal&#39;s global advisory board for sustainability and social impact.
      - Analisa has been recognized as a UBS Global Visionary, Young Global Leader (by the World Economic Forum), and 100 Most Influential Filipinas of the World (by FWN). She has been honored with the Madam C.J. Walker Leadership Award by US National Minority Business Council, and Distinguished Leader Award by UN Women New York Chapter.

# mentors:

saturday:
  - time: 9:00 AM
    name: Doors Open
  - time: 9:30 AM
    name: Hacking Begins!
  - time: 10:00 AM
    name: Brunch
  - time: 4:00 PM
    name: Lunch / Dinner
sunday:
  - time: 9:00 AM
    name: Doors Open
  - time: 10:00 AM
    name: Brunch
  - time: 12:00 PM
    name: Project Submissions
  - time: 1:00 PM
    name: Project Presentations
  - time: 5:00 PM
    name: Judging
  - time: 5:30 PM
    name: Award Presentations
  - time: 5:45 PM
    name: Closing Remarks

awards:
  - name: Global Nominee
    globalNominee: true
    winners:
      - link: https://2018.spaceappschallenge.org/challenges/volcanoes-icebergs-and-asteroids-oh-my/dont-forget-can-opener/teams/smsafety/project
        challenge: Don't Forget the Can Opener!
        name: SMSafety
  - name: Global Nominee
    globalNominee: true
    winners:
      - link: https://2018.spaceappschallenge.org/challenges/what-world-needs-now/health-makes-wealth/teams/instaco2/project
        challenge: Health Makes Wealth
        name: InstaC02
  - name: Best Mission Concept
    winners:
      - link: https://2018.spaceappschallenge.org/challenges/universe-beauty-and-wonder/virtual-space-exploration/teams/stage-one/project
        challenge: Virtual Space Exploration
        name: Stage One
  - name: Galactic Impact
    winners:
      - link: https://2018.spaceappschallenge.org/challenges/what-world-needs-now/land-where-displaced-people-settle/teams/demeter/project
        challenge: The Land Where Displaced People Settle
        name: Demeter
  - name: Most Inspirational Hack
    winners:
      - link: https://2018.spaceappschallenge.org/challenges/volcanoes-icebergs-and-asteroids-oh-my/real-time-fire-app/teams/firecloud/project
        challenge: Spot That Fire!
        name: Firecloud
      - link: https://2018.spaceappschallenge.org/challenges/universe-beauty-and-wonder/virtual-space-exploration/teams/babblenauts/project
        challenge: Virtual Space Exploration
        name: Babbelnauts
  - name: Best Use of Hardware
    winners:
      - link: https://2018.spaceappschallenge.org/challenges/can-you-build/make-sense-out-mars/teams/absolute/project
        challenge: Make Sense Out Of Mars
        name: Absolute
  - name: Best Use of Data
    winners:
      - link: https://2018.spaceappschallenge.org/challenges/icy-glare/recycle-polar-opposites/teams/arctic-reality/project
        challenge: Polar Opposites
        name: Arctic Reality
  - name: Best Use of Science
    winners:
      - link: https://2018.spaceappschallenge.org/challenges/volcanoes-icebergs-and-asteroids-oh-my/real-time-fire-app/teams/this-team-is-on-fire/project
        challenge: Spot That Fire!
        name: This Team Is On Fire

organizers:
  - image: images/producers/JoeSpens_Headshot.png
    name: Joseph Spens
    title: Executive Director
    twitter: joespens
  - image: images/producers/DominiqueMorris_Headshot.jpg
    name: Dominique Morris
    title: Director
    linkedin: dominiquemorris1
  - image: images/producers/KatelynHertel_Headshot.jpg
    name: Katelyn Hertel
    title: Communications, Social Media Liason
    twitter: Katers_Potaters
  - image: images/producers/AnalisaBalares_Headshot.jpg
    name: Analisa Balares
    title: Strategic Partnerships
    twitter: analisabalares
  - image: images/producers/JolyMacfie_Headshot.jpg
    name: Joly MacFie
    title: Livestream
    linkedin: punkcast
  - image: images/producers/MikeCaprio_Headshot.jpg
    name: Mike Caprio
    title: Advisor
    twitter: mik3cap
pastOrganizers:
  - image: images/producers/AnitaCampbell_Headshot.jpg
    name: Anita Campbell
    title: Organizer
    twitter: anitanoodlesoup
  - image: images/producers/AliciaNoel_Headshot.jpg
    name: Alicia Noel
    title: Organizer
    twitter: aventureralicia
  - image: images/producers/CameraWalrond_Headshot.jpg
    name: Camera Walrond
    title: Conference
    twitter: camerawalrond
  - image: images/producers/RobertCarlsen_Headshot.jpg
    name: Robert Carlsen
    title: Operations
    website: robertcarlsen.net
  - image: images/producers/AmandaGhanooni_Headshot.jpg
    name: Amanda Ghanooni
    title: Organizer
    twitter: ghanooni
  - image: images/producers/AndrewLeung_Headshot.jpg
    name: Andrew Leung
    title: Sponsorship
    twitter: acl777
  - image: images/producers/WillVanWart_Headshot.jpg
    name: Will Van Wart
    title: Organizer
    twitter: will_van_wart
  - image: images/producers/AureliaMoser_Headshot.jpg
    name: Aurelia Moser
    title: Space Apps Brooklyn
    twitter: auremoser
  - image: images/producers/BrianRevak_Headshot.jpg
    name: Brian Revak
    title: Sponsorship
    twitter: brianrevak
  - image: images/producers/CarleenPan_Headshot.jpg
    name: Carleen Pan
    title: Organizer
    twitter: carleenlikes
  - image: images/producers/Kennedy_Headshot.jpg
    name: Christopher Kennedy
    title: Security
    twitter: kennedysgarage
  - image: images/producers/KatieO_Headshot.png
    name: Katie O
    title: Social Media
    twitter: redprotist
  - image: images/producers/GeorgeSivulka_Headshot.jpg
    name: George Sivulka
    title: Space Apps Next Gen
    twitter: astro_siv
organizingPartners:
  - url: womensphere.com
    logo: images/womensphere.jpg
    content:
      - Womensphere empowers women and girls to boldly envision, create brighter futures, and transform our world through innovative initiatives, impact-driven collaborations, and inspiring communities.
      - Founded in 2007, they invest in closing gender gaps and in empowering women and girls to create the future through leadership, innovation, sustainability, entrepreneurship, education, public leadership, and STEAM (science, technology, engineering, arts & design, mathematics). They foster communities of global and local change-makers, innovators, scientists, creators, entrepreneurs, educators, public leaders, and emerging leaders. They collaborate with great men, women, and institutions that champion gender equality and invest in women and girls.
  - url: empirespace.nyc
    logo: images/esl.png
    content:
      - Empire Space Labs accelerates technology startups that create space applications. We provide expert mentorship, starting resources, partner introductions and strategic relationships, business model advice and business development - all to help fledgling companies overcome the challenges of starting a business in the commercial space sector.
sponsorships:
  - name: Galactic
    sponsors:
      - logo: images/postman_logo.svg
        url: https://www.getpostman.com/
partners:
  - url: http://www.nss.com/
    logo: images/nss.jpg
    name: National Space Society
  - url: https://www.nyspacealliance.org/
    logo: images/NYSA.png
    name: New York Space Alliance
  - url: http://www.secondmuse.com/
    logo: images/secondmuse_lrg.png
    name: SecondMuse
  - url: http://go.sap.com/training-certification/university-alliances.html
    logo: images/sap.png
    name: SAP Next-Gen
  - url: http://www.amnh.org/
    logo: images/AMNH_clear.png
    name: American Museum of Natural History
  - url: http://www.amnh.org/learn-teach/adults/bridgeup-stem
    logo: images/bridgeupamnh_clear.png
    name: "AMNH BridgeUp: STEM"
  - url: http://stickermule.com/supports/nasanyc19-sponsorship
    logo: images/sticker_mule_logo.png
    name: "Sticker Mule"
  - url: https://www.isoc-ny.org
    logo: images/ISOCNY_Logo.png
    name: Internet Society NY
  - url: http://levinriegner.com/
    logo: images/LR_Black.png
    name: L&R
  - url: https://odsc.com
    logo: images/ODSC.png
    name: Open Data Science Conference
  - url: https://aldrinfoundation.org/
    logo: images/Aldrin Family Foundation.png
    name: Aldrin Family Foundation
  - url: http://www.sciencepartnershipfund.org/
    logo: images/spf.png
    name: Science Partnership Fund
  - url: http://www.siliconharlem.net/
    logo: images/silicon_harlem.png
    name: Silicon Harlem
  - url: https://nycfirst.org
    logo: images/NYC FIRST.jpg
    name: NYC FIRST
videos:
  - name: 2018 Bootcamp & Demos
    url: https://www.youtube.com/playlist?list=PLTP4bRgnFNn3K3aGJSv4ziFWf7GNhrqPT
  - name: 2018 Promotion
    url: https://vimeo.com/258707552
  - name: 2017 Conference &amp; Demos
    url: https://www.youtube.com/playlist?list=PLTP4bRgnFNn2uwkUjIzrkRGrMq9oG9xRO
  - name: 2016 Conference &amp; Demos
    url: https://www.youtube.com/playlist?list=PLTP4bRgnFNn1IkKzd9cxHg2328oOvcqgv
  - name: 2015 Conference &amp; Demos
    url: https://www.youtube.com/playlist?list=PLTP4bRgnFNn3hezhb0DNqE65T6-PJM9L2
  - name: 2014 Bootcamp &amp; Demos
    url: https://www.youtube.com/playlist?list=PL009Ccd_L9NkqsV3oeje3mEDNmztcr2JJ
  - name: 2014 Promotion
    url: https://www.youtube.com/watch?v=VJkjtfTTfRI&feature=youtu.be
  - name: 2013 Hackathon
    url: http://www.youtube.com/playlist?list=PL009Ccd_L9NmGk94htU0ujhY5tHiabwQ7
press:
  - name: Forbes
    url: https://www.forbes.com/sites/chadorzel/2016/05/27/commercialization-of-space-three-cheers-for-the-mundane/#501139132f31
  - name: Space.com
    url: https://www.space.com/25456-nasa-space-apps-challenge-preview.html
  - name: Popular Mechanics
    url: https://www.popularmechanics.com/space/how-to/a11066/how-to-make-nasa-cool-again-17087616/
  - name: Rebranding by Levin Riegner
    url: https://levinriegner.news/2017/04/26/lr-launches-space-apps-nyc-into-the-future-with-brand-redesign-ahead-of-hackathon-weekend/
  - name: NewSpace People
    url: http://www.newspacepeople.com/newspace/company-updates/newspace-people-interview-with-space-apps-nyc
  - name: Space Apps NYC Next Gen on Medium
    url: https://medium.com/@jmfbrooks/space-apps-nyc-next-gen-a-high-school-hackathon-out-of-this-world-d689acbd4b71
