# Site settings
title: Space Apps NYC
email: organizers@spaceapps.nyc
description: The NYC chapter of NASA's International Space Apps Challenge
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://spaceapps.nyc" # the base hostname & protocol for your site
twitter_username: spaceappsnyc
github_username: spaceappsnyc
registrationIsOpen: true
livestreamIsOpen: false
dates:
  - header: Begins
    timestamp: October_19_2018
  - header: Ends
    timestamp: October_21_2018
details:
  location:
    map: https://goo.gl/maps/ZbJaZT1rLw82
    addressLine1: 402 E 8th St
    addressLine2: New York, NY 10009
    logo: images/LES Girls Club.png
member_count: 2800

# Build settings
markdown: kramdown
exclude:
  - vendor
  - archive
plugins:
  - github-pages

# Development
host: 0.0.0.0

# Event Schedule
bootcamps:
  - name: Intro to Google Cloud Platform and AI/ML with Google
    image: /images/intro_to_google_cloud.jpg
    location:
      name: Silicon Harlem
      addressLine1: 2785 Frederick Douglass Boulevard
      addressLine2: New York, NY 10039
    info:
      - Come enjoy some pizza uptown and Google will give us an introduction to their Cloud Platform.
      - Google Cloud is a great tool for Space Apps Challenge hackers to have going into the hackathon, as it will streamline the development of your projects so that you can focus on the core concepts and not the project infrastructure.
      - Hackathon and bootcamp participants will receive free Cloud credits!
      - <a href="https://cloud.google.com/startups">https://cloud.google.com/startups</a>
      - Tejpaul Bhatia, Startup Program Lead for Google Cloud NY and former 3 time entrepreneur will join us and give an overview of the Google Cloud platform and a primer on Machine Learning. He will also be able to answer any questions you might have leading up to the hackathon.
    schedule:
      - time: 6:30pm
        name: Doors open / Food & Drinks
      - time: 7:00pm
        name: Opening remarks from event organizers
      - time: 7:15pm
        name: Google Cloud Platform 101
      - time: 8:00pm
        name: Break
      - time: 8:10pm
        name: Artificial Intelligence & Machine Learning with Google
      - time: 8:55pm
        name: Networking
    website: https://www.eventbrite.com/e/intro-to-google-cloud-and-aiml-with-google-tickets-50400881393
  - name: Intro to OpenSpace
    image: /images/intro_to_openspace.png
    location:
      name: Lower East Side Girls Club
      addressLine1: 402 E 8th St
      addressLine2: New York, NY 10009
    info:
      - OpenSpace is open source interactive data visualization software designed to visualize the entire known universe and portray our ongoing efforts to investigate the cosmos.
      - Funded in part by NASA, OpenSpace brings the latest techniques from data visualization research to the general public. OpenSpace supports interactive presentation of dynamic data from observations, simulations, and space mission planning and operations. OpenSpace works on multiple operating systems, with an extensible architecture powering high resolution tiled displays and planetarium domes, and makes use of the latest graphic card technologies for rapid data throughput. In addition, OpenSpace enables simultaneous connections across the globe, creating opportunity for shared experiences among audiences worldwide.
      - <a href="https://www.openspaceproject.com/">https://www.openspaceproject.com/</a>
    schedule:
      - time: 6:00pm
        name: Doors open
      - time: 6:30pm
        name: Opening remarks from event organizers
      - time: 6:45pm
        name: Intro to OpenSpace
      - time: 8:15pm
        name: Networking
    website: https://www.eventbrite.com/e/intro-to-openspace-tickets-50470789490

judges:
  - name: Analisa Balares
    title: CEO & Chief Innovation Officer
    organization: Womensphere
    photo: Analisa Balares.jpeg
    bio:
      - Analisa Leonor Balares is Founder, CEO, and Chief Innovation Officer of Womensphere, a global platform for empowering women and girls to use STEAM, leadership, and innovation to create the future and help achieve the Global Goals for Sustainable Development. Analisa curates the Womensphere Summits &amp; Festivals, and leads building the Womensphere Innovation Leadership Lab, Womensphere Incubator Network, and Womensphere Foundation. Previously, Analisa worked in Wall Street for Goldman Sachs, Morgan Stanley, and Milestone Capital, and in technology and social media for Microsoft and 85 Broads (now Ellevate). She is an alumna of Harvard Business School, Mount Holyoke College, and Lester Pearson United World College,
      - Analisa is also a NASA Datanaut, and an organizer of the NASA Space Apps Global Challenge for NYC. She serves as a Commissioner of the Women’s Refugee Commission, Advisory Board Member of Music Beyond, Member of Women’s Forum of New York and International Women’s Forum, and Academy Member of the Global Teacher Prize. She also served as a Member of the Harvard Women’s Leadership Board, and L&#39;Oreal&#39;s global advisory board for sustainability and social impact.
      - Analisa has been recognized as a UBS Global Visionary, Young Global Leader (by the World Economic Forum), and 100 Most Influential Filipinas of the World (by FWN). She has been honored with the Madam C.J. Walker Leadership Award by US National Minority Business Council, and Distinguished Leader Award by UN Women New York Chapter.
  - name: Sidney Nakahoto
    title: Cofounder and CEO
    organization: New York Space Alliance
    photo: Sidney Nakahoto.jpg
    bio:
      - Sidney N. Nakahodo is a leading authority in space entrepreneurship, and cofounder and CEO of the New York Space Alliance (NYSA). He is active in the academic setting as a faculty member of Columbia University. He is also a former fellow of Singularity University, a think-tank and accelerator based at NASA Ames Research Park, in Silicon Valley, and currently serves as its New York City Chapter Ambassador. Previously he worked with private sector development and carbon finance at the World Bank. Sidney holds an MIA from Columbia University’s School of International and Public Affairs (SIPA) and a B. Eng. in Materials Engineering from the University of Sao Paulo (Brazil). He is a graduate of Singularity University’s Global Solutions Program, which he attended on a Google-sponsored scholarship, and the Kiel Institute’s Advanced Studies Program in International Economic Policy (Germany).  Sidney speaks Portuguese and Spanish, is conversant in French and Italian, and has basic knowledge of German.
  - name: Noemi Derzsy
    title: Senior Inventive Scientist
    organization: AT&T Labs
    photo: Noemi Derzsy.jpg
    bio:
      - Holding a PhD in Physics and research background in Network Science and Computer Science, my interests revolve around the study of complex systems and complex networks through real-world data. Currently, I am a Senior Inventive Scientist at AT&T Labs within the Data Science and AI Research organization, doing lots of science with lots of data. I am also a NASA Datanaut and co-organizer of Women in Machine Learning and Data Science NYC chapter.

# mentors:
#   - name: Noemi Derzsy
#     title: Senior Inventive Scientist
#     organization: AT&T Labs
#     photo: Noemi Derzsy.jpg
#     bio:
#       - Holding a PhD in Physics and research background in Network Science and Computer Science, my interests revolve around the study of complex systems and complex networks through real-world data. Currently, I am a Senior Inventive Scientist at AT&T Labs within the Data Science and AI Research organization, doing lots of science with lots of data. I am also a NASA Datanaut and co-organizer of Women in Machine Learning and Data Science NYC chapter.

# conference:
#   - time: 8:00 AM
#     name: Doors Open / Breakfast
#   - time: 8:45 AM
#     name: Opening Remarks
#     speakers:
#       - Space Apps NYC
#       - SAP Next-Gen
#       - NASA
#       - SecondMuse
#   - time: 9:00 AM
#     name: "Opening Keynote: Dare to Dream"
#     speakers:
#       - Anousheh Ansari
#   - time: 9:30 AM
#     name: The New Golden Age of Human Spaceflight
#     speakers:
#       - Richard Garriott
#   - time: 10:00 AM
#     name: Making Space Matter
#     speakers:
#       - Matthew Pearce
#       - Danielle Wood
#       - Jeff Goldstein
#       - Jason Kendall
#   - time: 11:00 AM
#     name: "CASIS International Space Station: Benefits for Humanity"
#     speakers:
#       - Jennifer Lopez
#   - time: 11:30 AM
#     name: Health and Air Quality Applications of Earth Science Data
#     speakers:
#       - Shobhana Gupta
#   - time: 12:00 PM
#     name: Lunch
#   - time: 1:00 PM
#     name: Networking Hour
#   - time: 2:00 PM
#     name: Panel 2 - Earth and Space Entrepreneurship
#     speakers:
#       - Jennifer Lopez
#       - Sean Casey
#       - Dave Moser
#   - time: 3:00 PM
#     name: The Big Data Project
#     speakers:
#       - Shane Glass
#   - time: 3:15 PM
#     name: Message from Vint Cerf
#     speakers:
#       - Vint Cerf
#   - time: 3:30 PM
#     name: Networking
#   - time: 4:00 PM
#     name: OpenSpace
#     speakers:
#       - Carter Emmart
#       - Alex Bock
#   - time: 5:00 PM
#     name: Closing Remarks / Networking
#     speakers:
#       - Space Apps NYC
# bootcamp:
#   - time: 9:30 AM - 11:00 AM
#     name: Intro to Python for Data Science
#     speakers:
#       - Art Yudin
#   - time: 9:30 AM - 10:30 AM
#     name: Using data.world to find data, collaborate and power your apps
#     speakers:
#       - Len Fishman
#   - time: 10:30 AM - 11:00 AM
#     name: "Open NASA Data: From API to Data Analysis"
#     speakers:
#       - Noemi Derzsy
#   - time: 11:00 AM - 12:00 PM
#     name: "AWS and NASA: They're Just Like Us"
#     speakers:
#       - TBD
#   - time: 11:00 AM - 11:30 AM
#     name: Intro to 3D Technology
#     speakers:
#       - Alexander Meacham
#   - time: 11:30 AM - 12:00 PM
#     name: How to Turn Your Ideas into a Startup/ Pitches
#     speakers:
#       - Brittany Laughlin
#   - time: 12:00 PM - 1:00 PM
#     name: Lunch
#   - time: 1:00 PM - 2:00 PM
#     name: Modular Robots for Planetary Exploration
#     speakers:
#       - Reem Alattas
#   - time: 1:00 PM - 1:30 PM
#     name: "The Forest and the Trees: What makes an effective Product Manager?"
#     speakers:
#       - Ashley Stubblefield
#   - time: 1:30 PM - 4:00 PM
#     name: Virtual Reality, Augmented Reality & 360 with Unity®
#     speakers:
#       - Lex Dreitser
#   - time: 2:00 PM - 3:00 PM
#     name: Is That Magic? How to Make Things Sense, Blink and Beep
#     speakers:
#       - Leslie Birch
#   - time: 3:00 PM - 4:00 PM
#     name: "iOS/Swift: Build Your First Mobile App, 'Tip Calculator'"
#     speakers:
#       - TBD
saturday:
  - time: 8:00 AM
    name: Doors Open / Breakfast
  - time: 9:00 AM
    name: Opening Remarks
  - time: 9:30 AM
    name: Hacking Begins!
  - time: 12:30 PM
    name: Lunch
  - time: 6:30 PM
    name: Dinner
sunday:
  - time: 8:00 AM
    name: Doors Open / Breakfast
  - time: 1:00 PM
    name: Lunch / Project Submissions
  - time: 2:00 PM
    name: Project Presentations
  - time: 5:00 PM
    name: Judging
  - time: 5:30 PM
    name: Award Presentations
  - time: 6:00 PM
    name: Closing Remarks

# Awards
awards:
  - name: You Are My Sunshine
    winner:
      link: https://2017.spaceappschallenge.org/challenges/earth-and-us/you-are-my-sunshine/teams/proxima
      name: PROXIMA
      globalNominee: true
  - name: What's For Dinner?
    winner:
      link: https://2017.spaceappschallenge.org/challenges/earth-and-us/whats-dinner/teams/wastenot
      name: Waste Not!
      globalNominee: true
  - name: Best Mission Concept
    winner:
      link: https://2017.spaceappschallenge.org/challenges/warning-danger-ahead/and-you-can-help-fight-fires/teams/the-smokey-bears/project
      name: The Smokey Bears
  - name: Galactic Impact
    winner:
      link: https://2017.spaceappschallenge.org/challenges/our-ecological-neighborhood/migratory-travels-and-travel-stories/teams/wildlife-go-1/project
      name: Wildlife Go
  - name: Most Inspirational Hack
    winner:
      link: https://2017.spaceappschallenge.org/challenges/earth-and-us/pilots-plus/teams/will-you-die/project
      name: Will You Die
  - name: Best Use of Hardware
    winner:
      link: ht—tps://2017.spaceappschallenge.org/challenges/ideate-and-create/bring-your-own-solution/teams/issie/project
      name: ISSIE—Earth Magic
  - name: Best Use of Data
    winner:
      link: https://2017.spaceappschallenge.org/challenges/ideate-and-create/data-concierge/teams/unified-search
      name: Unified Search
  - name: Clarifai API Award
    winner:
      link: https://2017.spaceappschallenge.org/challenges/earth-and-us/whats-dinner/teams/terrabeast
      name: Terrabeast
      peoplesChoice: true

# Organizing Team
organizers:
  - image: images/producers/JoeSpens_Headshot.png
    name: Joseph Spens
    title: Executive Director
    twitter: joespens
  - image: images/producers/DominiqueMorris_Headshot.jpg
    name: Dominique Morris
    title: Director
    linkedin: dominiquemorris1
  - image: images/producers/AnitaCampbell_Headshot.jpg
    name: Anita Campbell
    title: Organizer
    twitter: anitanoodlesoup
  - image: images/producers/AnalisaBalares_Headshot.jpg
    name: Analisa Balares
    title: Strategic Partnerships
    twitter: analisabalares
  - image: images/producers/JolyMacfie_Headshot.jpg
    name: Joly MacFie
    title: Livestream
    linkedin: punkcast
  - image: images/producers/MikeCaprio_Headshot.jpg
    name: Mike Caprio
    title: Advisor
    twitter: mik3cap
pastOrganizers:
  - image: images/producers/AliciaNoel_Headshot.jpg
    name: Alicia Noel
    title: Organizer
    twitter: aventureralicia
  - image: images/producers/CameraWalrond_Headshot.jpg
    name: Camera Walrond
    title: Conference
    twitter: camerawalrond
  - image: images/producers/RobertCarlsen_Headshot.jpg
    name: Robert Carlsen
    title: Operations
    website: robertcarlsen.net
  - image: images/producers/AmandaGhanooni_Headshot.jpg
    name: Amanda Ghanooni
    title: Organizer
    twitter: ghanooni
  - image: images/producers/AndrewLeung_Headshot.jpg
    name: Andrew Leung
    title: Sponsorship
    twitter: acl777
  - image: images/producers/WillVanWart_Headshot.jpg
    name: Will Van Wart
    title: Organizer
    twitter: will_van_wart
  - image: images/producers/AureliaMoser_Headshot.jpg
    name: Aurelia Moser
    title: Space Apps Brooklyn
    twitter: auremoser
  - image: images/producers/BrianRevak_Headshot.jpg
    name: Brian Revak
    title: Sponsorship
    twitter: brianrevak
  - image: images/producers/CarleenPan_Headshot.jpg
    name: Carleen Pan
    title: Organizer
    twitter: carleenlikes
  - image: images/producers/Kennedy_Headshot.jpg
    name: Christopher Kennedy
    title: Security
    twitter: kennedysgarage
  - image: images/producers/KatieO_Headshot.png
    name: Katie O
    title: Social Media
    twitter: redprotist
  - image: images/producers/GeorgeSivulka_Headshot.jpg
    name: George Sivulka
    title: Space Apps Next Gen
    twitter: astro_siv
organizingPartners:
  - url: girlsclub.org
    logo: images/LES Girls Club.png
    content:
      - The Lower Eastside Girls Club (LESGC) connects girls and young women to healthy and successful futures. Their state-of-the-art center offers a safe haven with programs in the arts, sciences, leadership, entrepreneurship, and wellness for middle and high school girls. Programs are offered at no cost to girls and their families.
      - Their mission is to break the cycle of local poverty by training the next generation of ethical, entrepreneurial and environmental leaders.
      - LESGC members perceive opportunity, develop self-confidence, make the right relationship choices, grow academically, value wellness, and have the ability to enter college or the workforce as fully prepared and connected adults.
  - url: womensphere.com
    logo: images/womensphere.jpg
    content:
      - Womensphere empowers women and girls to boldly envision, create brighter futures, and transform our world through innovative initiatives, impact-driven collaborations, and inspiring communities.
      - Founded in 2007, they invest in closing gender gaps and in empowering women and girls to create the future through leadership, innovation, sustainability, entrepreneurship, education, public leadership, and STEAM (science, technology, engineering, arts & design, mathematics). They foster communities of global and local change-makers, innovators, scientists, creators, entrepreneurs, educators, public leaders, and emerging leaders. They collaborate with great men, women, and institutions that champion gender equality and invest in women and girls.
  - url: empirespace.nyc
    logo: images/esl.png
    content:
      - Empire Space Labs accelerates technology startups that create space applications. We provide expert mentorship, starting resources, partner introductions and strategic relationships, business model advice and business development - all to help fledgling companies overcome the challenges of starting a business in the commercial space sector.
sponsorships:
  - name: Intergalactic
    sponsors:
      - logo: images/google_cloud.png
        url: https://cloud.google.com/gcp
partners:
  - url: http://www.nss.com/
    logo: images/nss.jpg
    name: National Space Society
  - url: http://www.secondmuse.com/
    logo: images/secondmuse_lrg.png
    name: SecondMuse
  - url: http://go.sap.com/training-certification/university-alliances.html
    logo: images/sap.png
    name: SAP Next-Gen
  - url: http://www.amnh.org/
    logo: images/AMNH_clear.png
    name: American Museum of Natural History
  - url: http://www.amnh.org/learn-teach/adults/bridgeup-stem
    logo: images/bridgeupamnh_clear.png
    name: "AMNH BridgeUp: STEM"
  - url: https://www.isoc-ny.org
    logo: images/ISOCNY_Logo.png
    name: Internet Society NY
  - url: http://levinriegner.com/
    logo: images/LR_Black.png
    name: L&R
